name: Performance Problem
description: Report performance related problems or other areas of concern
body:
  - type: markdown
    attributes:
      value: |
        Before reporting performance problems here, please make sure you are on the latest version of Purpur.
  - type: input
    attributes:
      label: Spark link
      description: We ask that all Spark profilings are shared through a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.
      placeholder: Output of /spark profiler --timeout 300
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of issue
      description: Please describe your issue in detail.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Purpur version
      description: |
        Run `/version` on your server and **paste** the full, unmodified output here.
        "latest" is *not* a version; we require the output of `/version` so we can adequately track down the issue.
        Additionally, do NOT provide a screenshot, you MUST paste the entire output.
        <details>
        <summary>Example</summary>

        ```
        > version
        [18:58:15 INFO]: Checking version, please wait...
        [18:58:15 INFO]: This server is running Purpur version git-Purpur-1126 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
        [18:58:15 INFO]: You are running the latest version
        [18:58:15 INFO]: Previous version: git-Purpur-1120 (MC: 1.16.5)
        ```

        </details>
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I am running the latest version of Purpur available from https://purpurmc.org/downloads.
          required: true
        - label: I have searched for and ensured there isn't already an open issue regarding this.
          required: true
        - label: I ticked all the boxes without actually reading them
          required: false
        - label: My version of Minecraft is supported by Purpur.
          required: true
  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below, if any.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false
