name: PR Build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 8]

    steps:
    - uses: actions/checkout@v2.1.0

    - name: Get PR info
      run: echo ::set-env name=PR::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1.3.0
      with:
        java-version: ${{ matrix.java }}

    - uses: actions/cache@v1.1.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Patch Purpur
      run: |
        git config --global user.email "purpur-pr@example.com"
        git config --global user.name "Pupur PR"
        git submodule update --init --recursive
        ./purpur jar
        
    - uses: actions/upload-artifact@v2
      with:
        name: Purpur-PR${{ env.PR }}-JDK${{ matrix.java }}
        path: purpurclip.jar
